TOP = ../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#
ARCHIVE += status.tpl-arch
ARCHIVE += status_ch.tpl-arch
ARCHIVE += cpswTimingCore.tpl-arch
ARCHIVE += llrfHlsAsyn.archive

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
#
# End of File


